#!/bin/bash
ls -A --group-directories-first --quoting-style=shell-escape | sed 's@$@/@' | sed 's@/@@' | tr '\n' ',' | sed 's@,@\n@g' | sort -k1,1d -k2,2 | paste -sd, - | sed 's@,@,\n@g' | tr -d '\n' ; echo
